name: Update README
on:
  push:
  schedule:
    - cron: '* 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4.0.2

      - name: Run npm
        run: npm src/get_commits.js

      - name: Commit if changed
        run: |-
          git config --global user.name "Sir. Automation"
          git config --global user.email "auto@mate.com"
          git commit -am "Reporting for duty" || exit 0
          git push
