name: Update README
env:
  TOKEN: $({ secrets.GITHUB_TOKEN })
on:
  push:
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4.0.2

      - name: Install dependencies
        run: npm install

  update:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Update readme
        run: node src/get_commits.mjs

      - name: Commit if changed
        run: bash src/commit.bash
